name: ai-quansat
services:
  ai:
    image: quansat/ai
    pull_policy: build
    build:
      context: .
      dockerfile: ./dockerfile
      tags:
        - quansat/ai:latest
    environment:
      - PORT=${PORT:-3000}
      - ORIGIN=http://localhost:${PORT:-3000}
    networks:
      - ai-net
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - ai-data:/data

volumes:
  ai-data:

networks:
  ai-net:
    driver: bridge
